[General]
Name = minime
Class = 0x000100
DiscoverableTimeout = 0
PairableTimeout = 0
AutoEnable = true
FastConnectable = true
JustWorksRepairing = always
MultiProfile = multiple

[Policy]
AutoEnable = true
ResumeDelay = 2
ReconnectAttempts = 7
ReconnectIntervals = 1, 2, 4, 8, 16, 32, 64
AutoConnectTimeout = 60
