# NextUI Alpine platform configuration (aarch64, SDL2 KMSDRM, Panfrost GLES)

OPT = -O3 -Ofast -fomit-frame-pointer
CFLAGS = -mcpu=cortex-a53 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
SDL = SDL2
GL = GLES

# System, SDL2 & local toolchain includes
CFLAGS += -I/usr/include -I/usr/include/SDL2 -I$(PREFIX_LOCAL)/include
LDFLAGS = -L/usr/lib -L$(PREFIX_LOCAL)/lib

# Compiler definitions & libraries
CFLAGS += -DUSE_$(SDL) -DUSE_$(GL) -DGL_GLEXT_PROTOTYPES
LDFLAGS += -lSDL2 -lSDL2_image -lSDL2_ttf -lGLESv2 -ltinyalsa -lpthread -ldl -lm -lz -lsamplerate

# CMake toolchain file for libchdr
PLATFORM_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
export CMAKE_TOOLCHAIN_FILE ?= $(PLATFORM_DIR)/toolchain.cmake

