# NextUI Alpine platform configuration (aarch64, SDL2 KMSDRM, Panfrost GLES)

OPT = -O3 -Ofast -fomit-frame-pointer
CFLAGS = -mcpu=cortex-a53 -flto
SDL = SDL2
GL = GLES

# System & SDL2 includes
CFLAGS += -I/usr/include -I/usr/include/SDL2
LDFLAGS = -L/usr/lib

# Compiler definitions & libraries
CFLAGS += -DUSE_$(SDL) -DUSE_$(GL) -DGL_GLEXT_PROTOTYPES
LDFLAGS += -lSDL2 -lSDL2_image -lSDL2_ttf -lGLESv2 -ltinyalsa -lpthread -ldl -lm -lz
