# Minime ALSA configuration
# Dynamically load Bluetooth / USB audio route overrides when active

@hooks [
    {
        func load
        files [
            "/run/asoundrc"
            "/mnt/sdcard/.asoundrc"
        ]
        errors false
    }
]
